version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "felipe"
      MYSQL_PASSWORD: "senha123"
      MYSQL_ROOT_PASSWORD: "senha123"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - ./db-data:/var/lib/mysql
